server:
  port: 9101

spring:
  data:
    redis:
      host: ymson.dynu.net
      password: ghkdlxldA!12
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
