server:
  port: 9101

spring:
  data:
    redis:
      host: ymson.dynu.net
      password: ghkdlxldA!12
  jwt:
    secret: 1q2w3e!@
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false

data:
  cors:
    origins: http://localhost:4200, http://chat.ymson.ooguy.com